---
version: "3.8"
services:
  movies:
    image: yaduvendra15/movies1:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: yaduvendra15/train1:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: yaduvendra15/recharge1:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: yaduvendra15/dth1:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
